"""add bio and photo path to user table

Revision ID: 248445983949
Revises: 547906c78d0c
Create Date: 2020-02-12 16:00:25.661910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248445983949'
down_revision = '547906c78d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
